config/routes.rb
Rails.application.routes.draw do

  resources :quotes, except: %i(destroy update edit) do

    collection do
      get :best
    end

    member do
      put :like
      put :dislike
    end

  end

end

app/models/quote.rb
class Quote < ActiveRecord::Base

  BEST_RATING_BOUND = 1

  scope :best, -> { where('rating > ?', BEST_RATING_BOUND) }

  validates :description, presence: true

  def like!
    increment!(:rating)
  end

  def dislike!
    decrement!(:rating)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action :set_quote, only: [:show, :like, :dislike]

  def index
    @quotes = Quote.order(created_at: :desc)
  end

  def best
    @quotes = Quote.best.order(rating: :desc)
    render :index
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to @quote
    else
      render :new
    end
  end

  def like
    quote_service.like(@quote)
    render json: {
      success: true,
      rating: @quote.rating
    }
  end

  def dislike
    quote_service.dislike(@quote)
    render json: {
      success: true,
      rating: @quote.rating
    }
  end

  private

  def quote_service
    @quote_service ||= ::QuoteService.new(session)
  end

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:description, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Quotes
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .wrapper

      .menubar
        .submenu
          .title Цитаты:
          .links
            = link_to 'новые', quotes_path
            = link_to 'лучшие', best_quotes_path
            = link_to 'добавить', new_quote_path
      = yield

app/views/quotes/_form.html.slim
= form_for(@quote) do |f|

  - if @quote.errors.any?
    #error_explanation
      h2 = pluralize(@quote.errors.count, 'error')
      ul
        - @quote.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :description
    br
    = f.text_area :description, cols: '95', rows: '6'
  .actions
    = f.submit

app/views/quotes/_quote.html.slim
.quote
  .header
    .actions
      .like.JS-Rating data-url=like_quote_path(quote) +
      .rating.JS-Rating-value = quote.rating ? quote.rating : "???"
      .dislike.JS-Rating data-url=dislike_quote_path(quote) -

    .date = quote.created_at.to_formatted_s(:db)
    = link_to "##{quote.id}", quote, class: "id"

  .text = quote.description

app/views/quotes/index.html.slim
= render partial: "quote", collection: @quotes

app/views/quotes/new.html.slim
= render 'form'

app/views/quotes/show.html.slim
= render partial: @quote